public with sharing class FirstController {
    public FirstController() {
        System.debug('Hello World');
        System.debug('Another Debug');
        System.debug('Added Another Debug');
        System.debug('Added Another Debug');
        System.debug('Added Another Debug 2222');
        System.debug('Added Another Debug 22222');
        System.debug('Added Another Debug 222222');
    }
}
